### ISSUE TITLE
GSOC Page

### ISSUE THREAD

**Issue by fundies** [enigma-dev/Site#11]
I would like us to add a GSOC page to site for this year. I think it would be cool if we could grab any issues tagged with GSOC and parse them into the website. We can also add difficulty tags or whatever to the issues to make it easier to parse. I suck at web design but I was thinking something like this:

![image](https://user-images.githubusercontent.com/1312117/101681171-c3ee9980-3a2f-11eb-9793-068e774ae200.png)

(maybe fluff it up with google colors?)

in mind. We can check some other orgs pages to add some other text fluff too.

**Comment by JoshDreamland** [comment]
(done)
