### ISSUE TITLE
Sharing Links Leads to Captchas

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/Site#6]
So every SINGLE time I share a link to the site on Facebook it asks me to answer some quiz to prove I'm not a robot. It really sucks and I have no idea how long its been doing it, for way over a year I'm certain. This have something to do with our self-signed SSL certificate or something?

**Comment by JoshDreamland** [comment]
Our SSL cert is signed by a trusted third-party. Not Verisign, because I don't feel like spending thousands of dollars. But a big one. I think Facebook just makes you fill out a captcha anytime it doesn't recognize the URL (probably by frequency analysis).
