### ISSUE TITLE
Closing Parenthesis on Raw URLs causes wrong target

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/Site#7]
``https://en.wikipedia.org/wiki/Mach_(kernel)``

Failed to link to https://en.wikipedia.org/wiki/Mach_(kernel) in a forum post and instead linked to:

``https://en.wikipedia.org/wiki/Mach_(kernel``

Notice the missing enclosing parenthesis. I am not sure if this is our fault or we should shuffle this up to SMF. I discovered through a simple Google search that I can apparently escape an enclosing parenthesis with %29 and that works.

**Comment by JoshDreamland** [comment]
This is definitely SMF-side. We may just need to update; I haven't been good about keeping our forum software up-to-date.
