### ISSUE TITLE
Commit Ticker is Out of Date

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/Site#8]
![Old Commit](https://user-images.githubusercontent.com/3212801/34457807-af507902-ed8a-11e7-93ba-c292a43fce89.png)

It keeps displaying this old commit for months now.

**Comment by RobertBColton** [comment]
@JoshDreamland ping.

**Comment by JoshDreamland** [comment]
I could scarcely care less about this. Feel free to investigate.

**Comment by RobertBColton** [comment]
Lol, it looks like it's coming from the MySQL database: https://github.com/enigma-dev/Site/blob/e9f7aa4b06a1b8e79e727f8a983bf0d2fb248dac/site/functions.php#L16

Why would that be? Is it literally doing a git checkout and then storing commits into a MySQL database? Why not use the GitHub API?

**Comment by JoshDreamland** [comment]
Ah. Okay. This broke during server migration. I've updated the webhook.

**Comment by RobertBColton** [comment]
Thanks Josh!
